### ISSUE TITLE
[bug] 추억 저장시 날짜 미입력

### ISSUE THREAD

**Issue by keartt** [y-00jin/Chalkak#6]
날짜 미입력 추억 저장 시  아래 날짜로 저장됩니다.

![image](https://github.com/y-00jin/Chalkak/assets/83094369/cffb390e-0809-4934-a77f-6f6cd79ae341)

**Comment by y-00jin** [comment]
수정 완료입니다.

![image](https://github.com/y-00jin/Chalkak/assets/81798918/86260110-9c35-4b2b-a570-f7aa6b411749)

**Comment by keartt** [comment]
날짜 미입력시 오늘 날짜로 하는게 좋지 않을까요?

**Comment by y-00jin** [comment]
다녀온 추억 장소를 저장하는 건데 날짜가 기억 안날수도 있잖아요ㅎㅎ
